### ISSUE TITLE
Historical Oil Production Screen

### ISSUE THREAD

**Issue by OpenOilUG** [JesperWe/gffr-portal#166]
![Image](https://user-images.githubusercontent.com/8157224/188920886-def08ea0-255e-4bf1-83df-766a66bc0eea.png)

**Comment by OpenOilUG** [comment]
NOTE. THE SAME TASKS APPLY ALSO TO HISTORIC GAS PRODUCTION AND HISTORIC COAL PRODUCTION

1 - Download button inactive
2 - Link to data sources inactive
3 - Information buttons on individual sources inactive
4 - Country name should be repeated: "Australia Historical Oil Production"

**Comment by OpenOilUG** [comment]
Information buttons link to newly created Terms in POEditor:
EIA = eia
BP = bp
OPEC = opec

**Comment by OlegKozlovskui** [comment]
@OpenOilUG 
1 - button was hidden for now
2, 4 - done
