### ISSUE TITLE
Historical Oil Reserves Screen

### ISSUE THREAD

**Issue by OpenOilUG** [JesperWe/gffr-portal#167]
![Image](https://user-images.githubusercontent.com/8157224/188926518-b5b5e32c-603b-4137-a9f0-dc4b4dc1955f.png)

**Comment by OpenOilUG** [comment]
1 - Download button inactive
2 - Country name should be repeated
3 - Link to data inactive
4 - Information icons on sources inactive

PLEASE NOTE. SAME APPLIES TO HISTORIC GAS RESERVES AND HISTORIC COAL RESERVES

**Comment by OpenOilUG** [comment]
Information buttons link to newly created Terms in POEditor:
EIA = eia
BP = bp
OPEC = opec

**Comment by OlegKozlovskui** [comment]
@OpenOilUG 
1 - button was hidden for now
2, 4 - done

**Comment by OlegKozlovskui** [comment]
@niklaserik pls add Information icons

**Comment by niklaserik** [comment]
Information text is now added
